[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "../**",
  "dist/**",
  ".temp/**",
  "src/types.ts",
]
coverageThreshold = { lines = 0.99, functions = 0.99, statements = 0.99 }
