import { SQL } from "bun";
import type { DatabaseTypeType, PostgresDataSourceOptionsType } from "../../types";
import type { ColumnMetadata } from "../EntityMetadata";
import type { QueryRunner } from "../QueryRunner";
import { AbstractDriver, isJsonColumn, typeName } from "./AbstractDriver";

const TYPE_ALIASES: Readonly<Record<string, string>> = {
  int: "integer",
  int4: "integer",
  int2: "smallint",
  int8: "bigint",
  decimal: "numeric",
  number: "numeric",
  float: "double precision",
  float8: "double precision",
  double: "double precision",
  float4: "real",
  char: "character",
  varchar: "character varying",
  string: "character varying",
  time: "time without time zone",
  timetz: "time with time zone",
  timestamp: "timestamp without time zone",
  timestamptz: "timestamp with time zone",
  datetime: "timestamp without time zone",
  bool: "boolean",
  "simple-array": "text",
  "simple-json": "text",
  "simple-enum": "text",
  blob: "bytea",
  tinyint: "smallint",
  mediumint: "integer",
  tinytext: "text",
  mediumtext: "text",
  longtext: "text",
};

const escapePgArrayElement = (value: unknown): string => {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (typeof value === "number" || typeof value === "bigint") {
    return String(value);
  }

  if (typeof value === "boolean") {
    return value ? "t" : "f";
  }

  if (Array.isArray(value)) {
    return pgArrayLiteral(value);
  }

  const text =
    value instanceof Date ? value.toISOString() : typeof value === "object" ? JSON.stringify(value) : String(value);

  return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
};

/** A PostgreSQL array literal such as `{"a","b"}`; text input works for any element type. */
export const pgArrayLiteral = (values: unknown[]): string => `{${values.map(escapePgArrayElement).join(",")}}`;

/** Parses a one-dimensional PostgreSQL array literal back into strings (or nulls). */
export const parsePgArray = (text: string): (string | null)[] => {
  const items: (string | null)[] = [];
  let current = "";
  let quoted = false;
  let wasQuoted = false;
  let hasItem = false;

  const flush = (): void => {
    if (!hasItem) {
      return;
    }

    items.push(!wasQuoted && current === "NULL" ? null : current);
    current = "";
    wasQuoted = false;
    hasItem = false;
  };

  for (let index = 1; index < text.length; index += 1) {
    const char = text[index] ?? "";

    if (quoted) {
      if (char === "\\") {
        current += text[index + 1] ?? "";
        index += 1;
      } else if (char === '"') {
        quoted = false;
      } else {
        current += char;
      }

      continue;
    }

    if (char === '"') {
      quoted = true;
      wasQuoted = true;
      hasItem = true;
    } else if (char === "," || char === "}") {
      flush();
    } else {
      current += char;
      hasItem = true;
    }
  }

  return items;
};

export class PostgresDriver extends AbstractDriver {
  public readonly type: DatabaseTypeType = "postgres";
  public readonly supportsReturning = true;
  public readonly supportsIlike = true;
  public readonly supportsReservedConnections = true;
  public readonly supportsCreateIndexIfNotExists = true;

  public override escapePath(tableName: string, schema?: string | undefined): string {
    return super.escapePath(tableName, schema ?? (this.options as PostgresDataSourceOptionsType).schema);
  }

  /** JSON and array values are bound as text; the cast lets the server accept them for the column type. */
  public override parameterCast(column?: ColumnMetadata): string {
    if (column && isJsonColumn(column) && column.type !== "simple-json") {
      return `::${typeName(column.type)}`;
    }

    if (column?.isArray) {
      return `::${this.normalizeType(column)}`;
    }

    return "";
  }

  public normalizeType(column: ColumnMetadata): string {
    const name = typeName(column.type);
    let base: string;

    if (column.type === Number) {
      base = "integer";
    } else if (column.type === String) {
      base = "character varying";
    } else if (column.type === Boolean) {
      base = "boolean";
    } else if (column.type === Date) {
      base = "timestamp without time zone";
    } else if (name === "enum") {
      base = "text";
    } else {
      base = TYPE_ALIASES[name] ?? name;
    }

    return `${this.typeSuffix(column, base)}${column.isArray ? "[]" : ""}`;
  }

  public generatedColumnDefinition(column: ColumnMetadata): string | undefined {
    switch (column.generationStrategy) {
      case "increment":
      case "rowid":
        return typeName(column.type) === "bigint" ? "BIGSERIAL" : "SERIAL";
      case "identity":
        return `${this.normalizeType(column)} GENERATED BY DEFAULT AS IDENTITY`;
      case "uuid":
        return "uuid DEFAULT gen_random_uuid()";
      default:
        return undefined;
    }
  }

  public isInlinePrimaryKey(_column: ColumnMetadata): boolean {
    return false;
  }

  public currentTimestamp(): string {
    return "now()";
  }

  public buildLimitOffset(limit?: number, offset?: number): string {
    const parts: string[] = [];

    if (limit !== undefined) {
      parts.push(`LIMIT ${limit}`);
    }

    if (offset !== undefined) {
      parts.push(`OFFSET ${offset}`);
    }

    return parts.join(" ");
  }

  public buildCountDistinct(expressions: string[]): string {
    return expressions.length === 1
      ? `COUNT(DISTINCT ${expressions[0]})`
      : `COUNT(DISTINCT (${expressions.join(", ")}))`;
  }

  public createClient(): SQL {
    const options = this.options as PostgresDataSourceOptionsType;
    const extra = { ...options.extra };
    const idleTimeoutMillis = extra.idleTimeoutMillis as number | undefined;
    const connectionTimeoutMillis = extra.connectionTimeoutMillis as number | undefined;
    delete extra.idleTimeoutMillis;
    delete extra.connectionTimeoutMillis;

    return new SQL({
      adapter: "postgres",
      ...(options.url
        ? { url: options.url }
        : {
            hostname: options.host ?? "localhost",
            port: options.port ?? 5432,
            username: options.username ?? "postgres",
            password: options.password ?? "",
            database: options.database ?? options.username ?? "postgres",
          }),
      max: options.poolSize ?? (extra.max as number | undefined) ?? 10,
      ...(idleTimeoutMillis !== undefined && { idleTimeout: Math.ceil(idleTimeoutMillis / 1000) }),
      ...((options.connectTimeoutMS ?? connectionTimeoutMillis) !== undefined && {
        connectionTimeout: Math.ceil((options.connectTimeoutMS ?? connectionTimeoutMillis ?? 0) / 1000),
      }),
      ...(options.ssl !== undefined && { tls: options.ssl }),
      ...(options.prepare !== undefined && { prepare: options.prepare }),
      ...(options.bigint !== undefined && { bigint: options.bigint }),
      ...extra,
    } as ConstructorParameters<typeof SQL>[0]);
  }

  public async afterConnect(_client: SQL): Promise<void> {}

  public async listTables(runner: QueryRunner): Promise<string[]> {
    const schema = (this.options as PostgresDataSourceOptionsType).schema;
    const result = await runner.query<{ table_name: string }>(
      `SELECT table_name FROM information_schema.tables WHERE table_schema = ${schema ? "$1" : "current_schema()"} AND table_type = 'BASE TABLE'`,
      schema ? [schema] : [],
    );

    return result.records.map((row) => row.table_name);
  }

  public async dropAllTables(runner: QueryRunner, tableNames: string[]): Promise<void> {
    for (const tableName of tableNames) {
      await runner.query(`DROP TABLE IF EXISTS ${this.escapePath(tableName)} CASCADE`);
    }
  }

  protected override prepareArray(values: unknown[]): unknown {
    return pgArrayLiteral(values);
  }

  protected override hydrateArray(value: unknown, column: ColumnMetadata): unknown {
    if (typeof value === "string" && value.startsWith("{")) {
      return super.hydrateArray(parsePgArray(value), column);
    }

    return super.hydrateArray(value, column);
  }
}
