export const CURRENCIES = [
  { code: "USD", name: "US Dollar", icon: "🇺🇸", symbol: "$" },
  { code: "EUR", name: "Euro", icon: "🇪🇺", symbol: "€" },
  { code: "GBP", name: "British Pound Sterling", icon: "🇬🇧", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", icon: "🇯🇵", symbol: "¥" },
  { code: "AUD", name: "Australian Dollar", icon: "🇦🇺", symbol: "A$" },
  { code: "CAD", name: "Canadian Dollar", icon: "🇨🇦", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", icon: "🇨🇭", symbol: "CHF" },
  { code: "CNY", name: "Chinese Yuan", icon: "🇨🇳", symbol: "¥" },
  { code: "INR", name: "Indian Rupee", icon: "🇮🇳", symbol: "₹" },
  { code: "RUB", name: "Russian Ruble", icon: "🇷🇺", symbol: "₽" },
  { code: "BRL", name: "Brazilian Real", icon: "🇧🇷", symbol: "R$" },
  { code: "ZAR", name: "South African Rand", icon: "🇿🇦", symbol: "R" },
  { code: "SEK", name: "Swedish Krona", icon: "🇸🇪", symbol: "kr" },
  { code: "NZD", name: "New Zealand Dollar", icon: "🇳🇿", symbol: "NZ$" },
  { code: "SGD", name: "Singapore Dollar", icon: "🇸🇬", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", icon: "🇭🇰", symbol: "HK$" },
  { code: "MXN", name: "Mexican Peso", icon: "🇲🇽", symbol: "$" },
  { code: "NOK", name: "Norwegian Krone", icon: "🇳🇴", symbol: "kr" },
  { code: "KRW", name: "South Korean Won", icon: "🇰🇷", symbol: "₩" },
  { code: "TRY", name: "Turkish Lira", icon: "🇹🇷", symbol: "₺" },
  { code: "AED", name: "UAE Dirham", icon: "🇦🇪", symbol: "د.إ" },
  { code: "SAR", name: "Saudi Riyal", icon: "🇸🇦", symbol: "﷼" },
  { code: "PLN", name: "Polish Zloty", icon: "🇵🇱", symbol: "zł" },
  { code: "DKK", name: "Danish Krone", icon: "🇩🇰", symbol: "kr" },
  { code: "THB", name: "Thai Baht", icon: "🇹🇭", symbol: "฿" },
  { code: "IDR", name: "Indonesian Rupiah", icon: "🇮🇩", symbol: "Rp" },
  { code: "MYR", name: "Malaysian Ringgit", icon: "🇲🇾", symbol: "RM" },
  { code: "PHP", name: "Philippine Peso", icon: "🇵🇭", symbol: "₱" },
  { code: "CZK", name: "Czech Koruna", icon: "🇨🇿", symbol: "Kč" },
  { code: "HUF", name: "Hungarian Forint", icon: "🇭🇺", symbol: "Ft" },
  { code: "ILS", name: "Israeli New Shekel", icon: "🇮🇱", symbol: "₪" },
  { code: "CLP", name: "Chilean Peso", icon: "🇨🇱", symbol: "$" },
  { code: "COP", name: "Colombian Peso", icon: "🇨🇴", symbol: "$" },
  { code: "ARS", name: "Argentine Peso", icon: "🇦🇷", symbol: "$" },
  { code: "VND", name: "Vietnamese Dong", icon: "🇻🇳", symbol: "₫" },
  { code: "EGP", name: "Egyptian Pound", icon: "🇪🇬", symbol: "£" },
  { code: "NGN", name: "Nigerian Naira", icon: "🇳🇬", symbol: "₦" },
  { code: "PKR", name: "Pakistani Rupee", icon: "🇵🇰", symbol: "₨" },
  { code: "KES", name: "Kenyan Shilling", icon: "🇰🇪", symbol: "KSh" },
  { code: "TWD", name: "New Taiwan Dollar", icon: "🇹🇼", symbol: "NT$" },
  { code: "GHS", name: "Ghanaian Cedi", icon: "🇬🇭", symbol: "₵" },
  { code: "MAD", name: "Moroccan Dirham", icon: "🇲🇦", symbol: "د.م." },
  { code: "TND", name: "Tunisian Dinar", icon: "🇹🇳", symbol: "د.ت" },
  { code: "DZD", name: "Algerian Dinar", icon: "🇩🇿", symbol: "د.ج" },
  { code: "XOF", name: "West African CFA Franc", icon: "🌍", symbol: "CFA" },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    icon: "🌍",
    symbol: "FCFA",
  },
  { code: "BWP", name: "Botswana Pula", icon: "🇧🇼", symbol: "P" },
  { code: "MUR", name: "Mauritian Rupee", icon: "🇲🇺", symbol: "₨" },
  { code: "ETB", name: "Ethiopian Birr", icon: "🇪🇹", symbol: "Br" },
  { code: "SDG", name: "Sudanese Pound", icon: "🇸🇩", symbol: "ج.س." },
  { code: "TZS", name: "Tanzanian Shilling", icon: "🇹🇿", symbol: "TSh" },
  { code: "UGX", name: "Ugandan Shilling", icon: "🇺🇬", symbol: "USh" },
  { code: "RWF", name: "Rwandan Franc", icon: "🇷🇼", symbol: "FRw" },
  { code: "CVE", name: "Cape Verdean Escudo", icon: "🇨🇻", symbol: "$" },
  { code: "SZL", name: "Swazi Lilangeni", icon: "🇸🇿", symbol: "L" },
  { code: "LSL", name: "Lesotho Loti", icon: "🇱🇸", symbol: "L" },
  { code: "MZN", name: "Mozambican Metical", icon: "🇲🇿", symbol: "MT" },
  { code: "AOA", name: "Angolan Kwanza", icon: "🇦🇴", symbol: "Kz" },
  { code: "MWK", name: "Malawian Kwacha", icon: "🇲🇼", symbol: "MK" },
  { code: "GMD", name: "Gambian Dalasi", icon: "🇬🇲", symbol: "D" },
  { code: "SLL", name: "Sierra Leonean Leone", icon: "🇸🇱", symbol: "Le" },
  { code: "SCR", name: "Seychellois Rupee", icon: "🇸🇨", symbol: "₨" },
  { code: "DJF", name: "Djiboutian Franc", icon: "🇩🇯", symbol: "Fdj" },
  { code: "SOS", name: "Somali Shilling", icon: "🇸🇴", symbol: "S" },
  { code: "MGA", name: "Malagasy Ariary", icon: "🇲🇬", symbol: "Ar" },
  { code: "BIF", name: "Burundian Franc", icon: "🇧🇮", symbol: "FBu" },
  { code: "KMF", name: "Comorian Franc", icon: "🇰🇲", symbol: "CF" },
  { code: "ERN", name: "Eritrean Nakfa", icon: "🇪🇷", symbol: "Nfk" },
  { code: "LYD", name: "Libyan Dinar", icon: "🇱🇾", symbol: "ل.د" },
  { code: "RON", name: "Romanian Leu", icon: "🇷🇴", symbol: "lei" },
  { code: "UAH", name: "Ukrainian Hryvnia", icon: "🇺🇦", symbol: "₴" },
  { code: "HRK", name: "Croatian Kuna", icon: "🇭🇷", symbol: "kn" },
  { code: "ISK", name: "Icelandic Krona", icon: "🇮🇸", symbol: "kr" },
  { code: "BGN", name: "Bulgarian Lev", icon: "🇧🇬", symbol: "лв" },
  { code: "MKD", name: "Macedonian Denar", icon: "🇲🇰", symbol: "ден" },
  { code: "RSD", name: "Serbian Dinar", icon: "🇷🇸", symbol: "дин" },
  { code: "MDL", name: "Moldovan Leu", icon: "🇲🇩", symbol: "L" },
  { code: "ALL", name: "Albanian Lek", icon: "🇦🇱", symbol: "L" },
  { code: "GEL", name: "Georgian Lari", icon: "🇬🇪", symbol: "₾" },
  { code: "BYN", name: "Belarusian Ruble", icon: "🇧🇾", symbol: "Br" },
  { code: "AZN", name: "Azerbaijani Manat", icon: "🇦🇿", symbol: "₼" },
  { code: "AMD", name: "Armenian Dram", icon: "🇦🇲", symbol: "֏" },
  { code: "KZT", name: "Kazakhstani Tenge", icon: "🇰🇿", symbol: "₸" },
  {
    code: "XDR",
    name: "Special Drawing Rights (IMF)",
    icon: "🏛️",
    symbol: "XDR",
  },
] as const;
