name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 2 * * 1" # Run Renovate every Monday at 2am UTC
  workflow_dispatch:
    # Allow manual triggering of Renovate

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write
  checks: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-cache-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            bun-cache-${{ runner.os }}-

      - run: bun install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      - run: bun run lint
      - run: bun run test

  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Validate Renovate config
        uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: "renovate.json"

  renovate:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch')
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.8
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
